---

## 4) GitHub Action to auto-update “Last Update”

### Workflow file: `.github/workflows/update-readme.yml`

```yaml
name: Update README Index

on:
  schedule:
    - cron: "15 5 * * *"   # daily at 05:15 UTC
  workflow_dispatch: {}
  push:
    paths:
      - "projects/**"
      - "scripts/update_readme.py"
      - "README.md"

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install --upgrade pip requests python-dateutil

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_SLUG: ${{ github.repository }}
        run: python scripts/update_readme.py

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-update Last Update column"
            git push
          else
            echo "No changes."
          fi
